name: Deploy Website Build

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
    paths:
      - apps/website/**

jobs:
  build-and-deploy:
    name: Test and Build and Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Test and Build Monorepo
        uses: ./.github/actions/test-and-build-monorepo-action
        with:
          run-build: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/website/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Set output
        run: echo "page_url=${{ steps.deployment.outputs.page_url }}" >> $GITHUB_ENV
